"""S3 (1.4) — NET / E2E witness for the rifle rig-retarget (Path A).

This slice is the END-TO-END witness over the whole Path A chain (resolver ->
read-reroute lowering -> binding-present verifier -> fixture), proving on the
REAL pipeline shape — not synthetic stubs — that the rifle binding is rerouted
through the per-instance rig resolver and seats under the ``_MainCameraRig``'s
``WeaponSlot``.

Three acceptance pillars (design-phase1 §5 S3 / §4 (d), (e), (g)):

1. **Deterministic RACE test (acceptance d)** — the crux the back-fill design
   LOST: Awake runs with the rig ABSENT -> the rig Model streams in LATE ->
   equip (``GetRifle``) fires -> the rifle ends up parented under the rig's
   ``WeaponSlot``. We run the REAL emitted ``Player:_resolveWeaponSlot()`` (the
   exact Luau the lowering produces, extracted from a live lowering — NOT a
   re-typed copy) under an executable ``luau`` harness with a deterministic
   Roblox-API stub. ``task.wait`` is the deterministic clock: the rig is inserted
   on a chosen tick INSIDE the bounded retry, so the first sweep misses and the
   retry catches it — forced, no flake. Proves the read-reroute resolver seats
   the binding under the deterministic failing schedule.

2. **Deterministic BOUNDARY-FAILS-LOUD test (acceptance e / e-boundary)** — a
   conversion-shaped source where the AI factors the field OUT of the read path
   (or emits an unsupported boundary form) drives the WHOLE pipeline gate (the
   real ``Pipeline._run_contract_verifier`` hook, same hook the corpus gate
   uses) and asserts the project FAIL-CLOSES LOUD: a promoted
   ``rig_binding_present`` error flips ``conversion success`` to False. This is
   the fail-closed boundary firing END-TO-END (pipeline level), not just in a
   unit — Path A's generality mechanism (fix-or-flag, never silently ship a
   wrong rifle).

3. **Fresh-conversion E2E (acceptance g — conversion half)** — asserts on the
   REAL captured pipeline OUTPUT (the corpus fixture regenerated by S2 from a
   real pipeline run, the conversion-output source of truth) that on the LIVE AI
   shape the Player ``rig_binding`` is ``present=True``, the consumer reads are
   rerouted to ``self:_resolveWeaponSlot()``, and the resolver targets the
   ``_MainCameraRig``'s ``WeaponSlot``. A ``@pytest.mark.slow`` test does the
   genuinely-fresh full conversion when the test-projects root is configured.
   *Design intent (load-bearing):* this asserts the read-reroute fires on the
   REAL live AI-output shape, the exact case the old write-anchored lowering
   abstained on (D-S2-REDESIGN).

GENERIC: every load-bearing assertion keys on the carrier's parameterized
``field``/``child`` (read from the fixture / fact), NOT on ``rifle``/
``weaponSlot``/``WeaponSlot``/``Camera`` string literals — where a SimpleFPS name
appears it is the fixture's DATA, not a hardcoded mechanism.

The LIVE Roblox Studio gameplay witness (PlaceTo / playtest) is run SEPARATELY
from the main session — Roblox MCP tools are not available in this subagent
context (e2e-studio-half-needs-main-session) — so this file asserts on the
converted OUTPUT artifacts, never on a live Studio session.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from converter.child_ref_resolver import (  # noqa: E402
    ChildRefScript,
    RigRootedRetargetFact,
)
from converter.contract_verifier import fail_closed_errors, verify_contract  # noqa: E402
from converter.pipeline import Pipeline  # noqa: E402
from converter.rifle_rig_retarget_lowering import lower_rifle_rig_retarget  # noqa: E402
from core.roblox_types import RbxPlace, RbxScript  # noqa: E402
from utils.luau_analyze import luau_analyze_path  # noqa: E402

_FIXTURE_ROOT = Path(__file__).parent / "fixtures" / "contract_corpus"
_SIMPLEFPS_FIXTURE = _FIXTURE_ROOT / "SimpleFPS" / "fixture.json"
_TOPOLOGY = {"modules": {"Player": {"stem": "Player"}}}


# ---------------------------------------------------------------------------
# Shared drivers (real lowering + real pipeline gate).
# ---------------------------------------------------------------------------
class _Script:
    """Minimal ``_HasLuauSourceAndPath`` for driving the REAL lowering."""

    def __init__(self, source: str, source_path: str = "/proj/Player.cs") -> None:
        self.luau_source = source
        self.source_path = source_path
        self.rig_binding: dict[str, object] | None = None


def _lower(
    source: str,
    *,
    field: str = "weaponSlot",
    child: str = "WeaponSlot",
    cam_receiver: str = "cam",
    source_path: str = "/proj/Player.cs",
) -> _Script:
    """Run S1's REAL lowering over ``source``; return the edited script object."""
    s = _Script(source, source_path)
    fact = RigRootedRetargetFact(
        field_name=field, child_name=child, cam_receiver=cam_receiver
    )
    crs = ChildRefScript(
        facts=(), getchild_total=1, resolved_total=1, rig_facts=(fact,)
    )
    lower_rifle_rig_retarget([s], {source_path: crs})
    return s


def _run_pipeline_gate(
    scripts: list[RbxScript], tmp_path: Path
) -> tuple[list[str], list[dict[str, object]]]:
    """Drive the REAL ``Pipeline._run_contract_verifier`` hook (the same gate the
    corpus uses) and return ``(promoted_fail_closed_errors, recorded_rows)`` — the
    LOUD end-to-end failure surface a dropped/un-rerouted binding produces."""
    unity_project = tmp_path / "unity"
    (unity_project / "Assets").mkdir(parents=True)
    output = tmp_path / "out"
    output.mkdir()
    pipeline = Pipeline(str(unity_project), str(output))
    pipeline.state.rbx_place = RbxPlace()
    pipeline.state.rbx_place.scripts = scripts
    pipeline.ctx.scene_runtime = {}
    pipeline._run_contract_verifier({"topology": _TOPOLOGY})
    rows = pipeline.ctx.scene_runtime.get("contract_check_violations", [])
    # The fail-closed promotion is what flips conversion success — compute it the
    # same way the verifier's pure surface does (the hook records the rows; the
    # promotion set is derived by fail_closed_errors over the same checks).
    result = verify_contract(_TOPOLOGY, scripts)
    return fail_closed_errors(result), rows


# The on-corpus AI-output shape (mirrors the captured live Player): the Awake
# camera-child write + the GetRifle consumer reads + the ``return Player``
# epilogue. ``cam`` is the bare symbol seeded from ``Camera.main.transform``.
_AI_OUTPUT_SHAPE = """local Player = {}
Player.__index = Player

function Player.new()
    local self = setmetatable({}, Player)
    return self
end

function Player:Awake()
    self.cam = workspace.CurrentCamera
    self.weaponSlot = self.cam and self.cam:GetChildren()[1]
end

function Player:GetRifle()
    local rifle = self.host.instantiatePrefab(self.riflePrefab, self.weaponSlot, pivotOf(self.weaponSlot))
    if self.weaponSlot then rifle:PivotTo(pivotOf(self.weaponSlot)) end
    return rifle
end

return Player
"""


# ===========================================================================
# 1. DETERMINISTIC RACE TEST (acceptance d) — the crux.
# Awake-miss -> rig streams in LATE -> equip -> rifle on the rig's WeaponSlot.
# Runs the REAL emitted resolver under an executable ``luau`` harness.
# ===========================================================================
def _extract_resolver_method(field: str = "weaponSlot", child: str = "WeaponSlot") -> str:
    """Extract the EXACT ``function <Class>:_resolve<Child>() ... end`` the REAL
    lowering emits (not a re-typed copy), so the harness exercises shipped Luau."""
    src = _AI_OUTPUT_SHAPE
    if field != "weaponSlot":
        src = src.replace("weaponSlot", field)
    lowered = _lower(src, field=field, child=child)
    method = re.search(
        rf"function Player:_resolve{re.escape(child)}\(\).*?\n    return slot[^\n]*\nend",
        lowered.luau_source,
        re.S,
    )
    assert method is not None, "could not extract the emitted resolver method"
    return method.group(0)


# A deterministic Roblox-API stub: ``task.wait`` is the clock. The rig Model is
# inserted into ``workspace`` ON a chosen tick INSIDE the bounded retry, so the
# first ``findSlot()`` sweep MISSES (Awake-with-rig-absent) and the retry catches
# the late-streaming rig. The whole schedule is forced — no real time, no flake.
def _race_harness(resolver_method: str, *, rig_appears_on_tick: int,
                  child: str = "WeaponSlot") -> str:
    return f"""
-- ===== Deterministic Roblox-API stub (task.wait is the clock) =====
local WORKSPACE_CHILDREN = {{}}
local TICK = 0
local RIG_APPEARS_ON_TICK = {rig_appears_on_tick}

local function makeInstance(className, attrs)
    local inst
    inst = {{
        _class = className,
        _attrs = attrs or {{}},
        _children = {{}},
        Parent = nil,
        IsA = function(self, c) return self._class == c end,
        GetAttribute = function(self, k) return self._attrs[k] end,
        GetChildren = function(self) return self._children end,
        FindFirstChild = function(self, name, _recursive)
            local function walk(node)
                for _, ch in node._children do
                    if ch._name == name then return ch end
                    local found = walk(ch)
                    if found then return found end
                end
                return nil
            end
            return walk(self)
        end,
    }}
    return inst
end

-- The rig Model + its WeaponSlot child (the late-streaming target).
local weaponSlot = makeInstance("BasePart", {{}})
weaponSlot._name = "{child}"
local rig = makeInstance("Model", {{ _MainCameraRig = true }})
rig._name = "_MainCameraRig"
weaponSlot.Parent = rig
rig._children = {{ weaponSlot }}

-- workspace:GetDescendants() flattens whatever has streamed in so far.
local workspace = {{
    CurrentCamera = makeInstance("Camera", {{}}),
    GetDescendants = function(self)
        local out = {{}}
        local function collect(node)
            for _, ch in node._children do
                table.insert(out, ch)
                collect(ch)
            end
        end
        for _, top in WORKSPACE_CHILDREN do
            table.insert(out, top)
            collect(top)
        end
        return out
    end,
}}

-- task.wait is the deterministic clock: it advances TICK and, on the chosen
-- tick, STREAMS THE RIG IN (the late-arrival the bounded retry exists for).
local task = {{
    wait = function(_dt)
        TICK = TICK + 1
        if TICK == RIG_APPEARS_ON_TICK then
            table.insert(WORKSPACE_CHILDREN, rig)
        end
        return _dt
    end,
}}

-- ===== The REAL emitted resolver, verbatim from the lowering =====
local Player = {{}}
Player.__index = Player
{resolver_method}

-- ===== Drive the failing schedule =====
local self = setmetatable({{}}, Player)

-- (1) Awake runs with the rig ABSENT (no _MainCameraRig in workspace yet).
--     A non-yielding lifecycle sweep would resolve nil here.
assert(#workspace:GetDescendants() == 0, "rig must be absent at Awake")

-- (2) equip fires (GetRifle / the yielding consumer) -> the resolver's first
--     sweep MISSES, the bounded retry runs, and the rig streams in on the
--     chosen tick -> the resolver returns the rig's WeaponSlot.
local slot = self:_resolve{child}()

-- (3) assert the rifle ends up parented under the rig's slot (NOT nil, NOT
--     workspace-origin) — the read reroute seats the binding under the race.
assert(slot ~= nil, "FAIL: resolver returned nil under the late-rig schedule")
assert(slot._name == "{child}", "FAIL: resolver returned the wrong child")
assert(slot.Parent == rig, "FAIL: slot is not under the _MainCameraRig")
assert(slot.Parent:GetAttribute("_MainCameraRig") == true,
    "FAIL: parent is not the rig")

-- the rifle would be parented here (the consumer's PivotTo / .Parent = slot):
local rifle = makeInstance("Model", {{}})
rifle.Parent = slot
assert(rifle.Parent == weaponSlot, "FAIL: rifle did not seat under WeaponSlot")

-- (4) memoization: a SECOND resolve returns the SAME cached instance (the warm
--     self._<field>Cache), and a fresh instance does NOT share the cache.
local slot2 = self:_resolve{child}()
assert(slot2 == slot, "FAIL: resolver is not memoized per-instance")
local other = setmetatable({{}}, Player)
-- the rig is already streamed in for the second instance; it resolves its OWN.
local other_slot = other:_resolve{child}()
assert(other_slot == weaponSlot, "FAIL: second instance did not resolve the slot")

print("RACE_OK")
"""


def _run_luau(source: str, timeout: float = 20.0) -> subprocess.CompletedProcess:
    f = tempfile.NamedTemporaryFile(
        mode="w", suffix=".luau", delete=False, encoding="utf-8"
    )
    path = f.name
    try:
        f.write(source)
        f.close()
        return subprocess.run(
            ["luau", path], capture_output=True, text=True, timeout=timeout
        )
    finally:
        Path(path).unlink(missing_ok=True)


def _luau_available() -> bool:
    from shutil import which

    return which("luau") is not None


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_awake_miss_then_late_rig_seats_under_weaponslot() -> None:
    """ACCEPTANCE (d) — THE CRUX. The rig is absent at Awake and streams in on a
    LATE tick (tick 5, well inside the 30-tick budget); the resolver's first sweep
    misses, the bounded retry catches the late rig, and the slot resolves under
    the ``_MainCameraRig``. Forced schedule, no flake. The back-fill design FAILED
    this; the consumer-side lazy resolve passes by construction."""
    resolver = _extract_resolver_method()
    harness = _race_harness(resolver, rig_appears_on_tick=5)
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"race harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_rig_present_before_first_sweep_resolves_synchronously() -> None:
    """ACCEPTANCE (d) variant — the rig is present BEFORE the first sweep (tick 1,
    the resolver's very first ``task.wait`` streams it in). The bounded retry's
    first tick catches it: a deterministic forced schedule, the other end of the
    interleaving (no flake either way)."""
    resolver = _extract_resolver_method()
    harness = _race_harness(resolver, rig_appears_on_tick=1)
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"early-rig harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


@pytest.mark.skipif(not _luau_available(), reason="luau interpreter not installed")
def test_race_generic_different_child_name_no_hardcode() -> None:
    """GENERIC — the SAME race passes for a DIFFERENT child name (``GunMount``),
    proving the harness keys on the carrier's ``child`` projection, not a
    hardcoded ``WeaponSlot`` mechanism. The emitted resolver + the lookup target
    are parameterized by the fact."""
    resolver = _extract_resolver_method(field="weaponSlot", child="GunMount")
    harness = _race_harness(resolver, rig_appears_on_tick=3, child="GunMount")
    proc = _run_luau(harness)
    assert proc.returncode == 0, (
        f"generic race harness FAILED:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    assert "RACE_OK" in proc.stdout, proc.stdout


# ===========================================================================
# 2. DETERMINISTIC BOUNDARY-FAILS-LOUD (acceptance e / e-boundary) — END-TO-END.
# A conversion-shaped source the lowering CANNOT discharge drives the REAL
# pipeline gate; the project FAIL-CLOSES LOUD (success -> False), never silently
# ships a wrong rifle.
# ===========================================================================
def test_boundary_field_factored_out_of_reads_fails_closed_end_to_end(
    tmp_path: Path,
) -> None:
    """ACCEPTANCE (e.ii) END-TO-END — the AI factors the field OUT of the read
    path (the write+return survive, but NO ``self.<field>`` consumer read remains
    to reroute). The lowering abstains (``present=False``); driven through the
    REAL ``_run_contract_verifier`` pipeline hook, the ``rig_binding_present``
    warning PROMOTES to a fail-closed error -> the project fail-closes LOUD."""
    # Run the REAL lowering on the shape — it abstains, stamping present=False.
    factored = (
        "function Player:Awake()\n"
        "    self.cam = workspace.CurrentCamera\n"
        "    self.weaponSlot = self.cam and self.cam:GetChildren()[1]\n"
        "end\n\n"
        "return Player\n"  # no consumer read of self.weaponSlot anywhere
    )
    lowered = _lower(factored)
    assert lowered.rig_binding == {
        "field": "weaponSlot", "child": "WeaponSlot", "present": False,
    }
    script = RbxScript(
        name="Player", source=lowered.luau_source, rig_binding=lowered.rig_binding
    )
    errs, rows = _run_pipeline_gate([script], tmp_path)
    # The boundary fired LOUD end-to-end: a promoted rig_binding_present error.
    assert any("rig_binding_present" in e for e in errs), (
        f"expected a fail-closed rig_binding_present error, got {errs}"
    )
    assert any("Player" in e for e in errs)
    assert any(r["check"] == "rig_binding_present" and r["severity"] == "warning"
               for r in rows)


def test_boundary_nonself_receiver_fails_closed_end_to_end(tmp_path: Path) -> None:
    """ACCEPTANCE (e-boundary.i) END-TO-END — an unsupported BOUNDARY form (a
    non-``self`` receiver read ``owner.weaponSlot`` surviving alongside the
    rerouted reads) is NOT silently passed. Driven through the real pipeline gate,
    the verifier's independent scan returns discharged=False -> a promoted
    ``rig_binding_present`` error -> fail-closed LOUD. A bare 'no self.<field>
    survives' check would FALSE-PASS this (the codex fail-open hole)."""
    green = _lower(_AI_OUTPUT_SHAPE)
    # Splice a surviving non-self boundary read into the yielding GetRifle.
    boundary_source = green.luau_source.replace(
        "    return rifle\nend",
        "    local x = owner.weaponSlot\n    return rifle\nend",
        1,
    )
    # The carrier still claims present=True (the lowering rerouted the dot reads),
    # but the INDEPENDENT scan must catch the surviving non-self read.
    script = RbxScript(
        name="Player",
        source=boundary_source,
        rig_binding={"field": "weaponSlot", "child": "WeaponSlot", "present": True},
    )
    errs, rows = _run_pipeline_gate([script], tmp_path)
    assert any("rig_binding_present" in e for e in errs), (
        f"boundary form must fail closed end-to-end, got {errs}"
    )


def test_boundary_discharged_binding_does_not_fail_closed(tmp_path: Path) -> None:
    """REGRESSION GUARD — a correctly discharged binding (the real lowered shape,
    present=True, reads rerouted, no surviving raw read) does NOT trip the gate:
    the fail-closed boundary is precise, not a blanket reject."""
    green = _lower(_AI_OUTPUT_SHAPE)
    script = RbxScript(
        name="Player", source=green.luau_source, rig_binding=green.rig_binding
    )
    errs, _ = _run_pipeline_gate([script], tmp_path)
    assert not any("rig_binding_present" in e for e in errs), (
        f"a discharged binding must NOT fail closed, got {errs}"
    )


# ===========================================================================
# 3. FRESH-CONVERSION E2E (acceptance g — conversion half).
# Assert on the REAL captured pipeline OUTPUT (the corpus fixture S2 regenerated
# from a real run) that on the LIVE AI shape the rifle binding is rerouted and
# seats under the rig's WeaponSlot. DESIGN INTENT: this asserts the read-reroute
# fires on the REAL live AI-output shape (the D-S2-REDESIGN case).
# ===========================================================================
def _load_fixture_player() -> tuple[dict, dict]:
    """Return ``(player_script_dict, rig_binding)`` from the captured SimpleFPS
    fixture — the real-pipeline conversion-output source of truth."""
    fx = json.loads(_SIMPLEFPS_FIXTURE.read_text(encoding="utf-8"))
    player = next(s for s in fx["scripts"] if s["name"] == "Player")
    rb = player.get("rig_binding")
    assert isinstance(rb, dict), "the captured Player must carry a rig_binding carrier"
    return player, rb


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_conversion_rifle_binding_present_on_live_shape() -> None:
    """ACCEPTANCE (g) — on the REAL captured pipeline output the Player binding is
    DISCHARGED present=True. This is the live AI shape the OLD write-anchored
    lowering abstained on (D-S2-REDESIGN: the cache collapsed the Camera.main
    ordinal to a non-ordinal write); Path A's read reroute discharges it. Keyed on
    the carrier's projections, not a hardcoded literal."""
    player, rb = _load_fixture_player()
    assert rb.get("present") is True, (
        "the captured Player rig_binding must be discharged present=True on the "
        "real live shape (the Path A read-reroute fires regardless of write shape)"
    )
    field = rb.get("field")
    child = rb.get("child")
    assert isinstance(field, str) and field, "carrier must carry a field projection"
    assert isinstance(child, str) and child, "carrier must carry a child projection"


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_reads_rerouted_to_resolver_targeting_rig() -> None:
    """ACCEPTANCE (g) — on the REAL captured output: the ``self.<field>`` consumer
    reads are rerouted to ``self:_resolve<Child>()`` AND the resolver targets the
    ``_MainCameraRig``'s ``<Child>`` slot. Derives the resolver/call names from the
    carrier's ``field``/``child`` so this stays GENERIC (no hardcoded mechanism)."""
    player, rb = _load_fixture_player()
    child = rb["child"]
    src = player["source"]
    resolver_def = f"function Player:_resolve{child}("
    resolver_call = f"self:_resolve{child}()"
    assert resolver_def in src, (
        f"the captured output must inject the per-instance resolver {resolver_def!r}"
    )
    assert resolver_call in src, (
        f"the captured output must reroute >=1 consumer read to {resolver_call!r}"
    )
    # The resolver seats on the rig: it scans for the _MainCameraRig attribute and
    # looks up the child by name under it (a real Instance via FindFirstChild).
    assert 'GetAttribute("_MainCameraRig")' in src, (
        "the resolver must target the _MainCameraRig Model (the rig anchor)"
    )
    assert f'FindFirstChild("{child}", true)' in src, (
        f"the resolver must look up the rig child {child!r} under the rig"
    )


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_conversion_independently_verifies_green() -> None:
    """ACCEPTANCE (g) — running the REAL verifier over the captured Player (with
    its real ``rig_binding`` carrier + real source) produces ZERO
    ``rig_binding_present`` rows: the independent source scan AGREES the binding
    landed. This proves the captured discharge is REAL, not a stamp-only claim —
    the verifier re-derives discharge from the captured source itself."""
    player, rb = _load_fixture_player()
    script = RbxScript(name="Player", source=player["source"], rig_binding=rb)
    res = verify_contract(_TOPOLOGY, [script])
    rig_rows = [v for v in res.violations if v.check == "rig_binding_present"]
    assert rig_rows == [], (
        f"the captured discharged binding must verify clean, got {rig_rows}"
    )
    assert not any("rig_binding_present" in e for e in fail_closed_errors(res))


@pytest.mark.skipif(
    not _SIMPLEFPS_FIXTURE.exists(), reason="SimpleFPS corpus fixture not present"
)
def test_e2e_captured_output_is_loadable_luau() -> None:
    """ACCEPTANCE (c-i, end-to-end) — the captured Player source (resolver spliced
    BEFORE ``return Player``) is valid, loadable Luau: the read reroute + the
    injected resolver did not produce unloadable output on the real shape."""
    if not luau_analyze_path():
        pytest.skip("luau-analyze not installed")
    from utils.luau_analyze import syntax_errors_for_source

    player, _ = _load_fixture_player()
    errs = syntax_errors_for_source(player["source"])
    assert errs == [], f"captured Player Luau has syntax errors: {errs}"


# ---------------------------------------------------------------------------
# The genuinely-FRESH full conversion (slow). Excluded from ``-m "not slow"``
# CI; the captured-fixture tests above are the fast conversion-output proof.
# ---------------------------------------------------------------------------
@pytest.mark.slow
def test_e2e_fresh_simplefps_conversion_seats_rifle_binding(tmp_path: Path) -> None:
    """ACCEPTANCE (g — FRESH) — a genuinely fresh generic SimpleFPS conversion
    through the REAL pipeline produces a Player module whose rifle binding is
    rerouted + present, seated under the ``_MainCameraRig``'s ``WeaponSlot``.

    Runs ONLY when the test-projects root is configured (``regen_contract_corpus``
    points at the populated main checkout); otherwise SKIPS — the fresh
    conversion needs the full Unity project the CI image does not carry. The fast
    captured-fixture tests above cover the conversion-output assertion for CI."""
    import os

    projects_root = os.environ.get("CONTRACT_CORPUS_PROJECTS_ROOT")
    if not projects_root or not Path(projects_root).exists():
        pytest.skip(
            "set CONTRACT_CORPUS_PROJECTS_ROOT to a populated test_projects root "
            "to run the fresh full SimpleFPS conversion"
        )

    # Drive the corpus regen (warm cache) — it runs the REAL pipeline end-to-end
    # and captures the live output, refusing to write on any real violation.
    repo_tools = Path(__file__).parent.parent / "tools" / "regen_contract_corpus.py"
    out_fixture = tmp_path / "fixture.json"
    proc = subprocess.run(
        [sys.executable, str(repo_tools), "SimpleFPS", "--out", str(out_fixture)],
        capture_output=True,
        text=True,
        env={**os.environ, "CONTRACT_CORPUS_PROJECTS_ROOT": projects_root},
        timeout=1800,
    )
    assert proc.returncode == 0, (
        f"fresh conversion/regen failed:\nstdout={proc.stdout}\nstderr={proc.stderr}"
    )
    fx = json.loads(out_fixture.read_text(encoding="utf-8"))
    player = next(s for s in fx["scripts"] if s["name"] == "Player")
    rb = player.get("rig_binding")
    assert isinstance(rb, dict) and rb.get("present") is True, (
        "a FRESH conversion must discharge the Player rifle binding present=True "
        "on the live AI shape (the Path A read reroute fires RHS-agnostically)"
    )
    child = rb["child"]
    src = player["source"]
    assert f"function Player:_resolve{child}(" in src
    assert f"self:_resolve{child}()" in src
    assert 'GetAttribute("_MainCameraRig")' in src
    assert f'FindFirstChild("{child}", true)' in src
